name: C/C++ CI
on: [push, pull_request]

jobs:
  build-i686-w64-mingw32-static:
    name: Build MXE i686-w64-mingw32.static
    runs-on: ubuntu-latest
    container: opensuse/leap:15.3
    steps:
      - uses: actions/checkout@v1.2.0
      - name: Add devel-tools-building repo
        run: zypper -n ar -c -f -n 'repo-devel-tools-building' https://download.opensuse.org/repositories/devel:/tools:/building/openSUSE_Leap_15.3/ repo-devel-tools-building
      - name: Update packages
        run: zypper -n --gpg-auto-import-keys ref
      - name: Upgrade packages
        run: zypper -n --gpg-auto-import-keys up
      - name: Install openSUSE dependencies
        run: zypper -n --gpg-auto-import-keys install glibc glibc-extra glibc-locale glibc-i18ndata glibc-32bit gcc10 gcc10-c++ shadow which patch gperf wget curl git diffutils make cmake libtool pkg-config autoconf automake makeinfo meson ninja intltool tar gzip bzip2 xz p7zip p7zip-full lzip zip unzip gtk-doc gettext-tools scons bison flex ruby orc linux-glibc-devel glibc-devel file-devel libopenssl-devel libffi-devel gdk-pixbuf-devel python3-base python3-Mako
      - name: update-alternatives
        run: |
          update-alternatives --install /usr/bin/cc cc /usr/bin/gcc-10 50
          update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-10 50
          update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 50
          update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 50
          update-alternatives --set cc /usr/bin/gcc-10
          update-alternatives --set c++ /usr/bin/g++-10
          update-alternatives --set gcc /usr/bin/gcc-10
          update-alternatives --set g++ /usr/bin/g++-10
      - name: Link python 3
        run: ln -s /usr/bin/python3 /usr/bin/python
      - name: Update settings.mk
        shell: bash
        run: sed -i 's/MXE_TARGETS := .*/MXE_TARGETS := i686-w64-mingw32.static/g' settings.mk
      - name: Compile
        shell: bash
        run: make -j4

  build-x86_64-w64-mingw32-static:
    name: Build MXE x86_64-w64-mingw32.static
    runs-on: ubuntu-latest
    container: opensuse/leap:15.3
    steps:
      - uses: actions/checkout@v1.2.0
      - name: Add devel-tools-building repo
        run: zypper -n ar -c -f -n 'repo-devel-tools-building' https://download.opensuse.org/repositories/devel:/tools:/building/openSUSE_Leap_15.3/ repo-devel-tools-building
      - name: Update packages
        run: zypper -n --gpg-auto-import-keys ref
      - name: Upgrade packages
        run: zypper -n --gpg-auto-import-keys up
      - name: Install openSUSE dependencies
        run: zypper -n --gpg-auto-import-keys install glibc glibc-extra glibc-locale glibc-i18ndata glibc-32bit gcc10 gcc10-c++ shadow which patch gperf wget curl git diffutils make cmake libtool pkg-config autoconf automake makeinfo meson ninja intltool tar gzip bzip2 xz p7zip p7zip-full lzip zip unzip gtk-doc gettext-tools scons bison flex ruby orc linux-glibc-devel glibc-devel file-devel libopenssl-devel libffi-devel gdk-pixbuf-devel python3-base python3-Mako
      - name: update-alternatives
        run: |
          update-alternatives --install /usr/bin/cc cc /usr/bin/gcc-10 50
          update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-10 50
          update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 50
          update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 50
          update-alternatives --set cc /usr/bin/gcc-10
          update-alternatives --set c++ /usr/bin/g++-10
          update-alternatives --set gcc /usr/bin/gcc-10
          update-alternatives --set g++ /usr/bin/g++-10
      - name: Link python 3
        run: ln -s /usr/bin/python3 /usr/bin/python
      - name: Update settings.mk
        shell: bash
        run: sed -i 's/MXE_TARGETS := .*/MXE_TARGETS := x86_64-w64-mingw32.static/g' settings.mk
      - name: Compile
        shell: bash
        run: make -j4

  build-i686-w64-mingw32-shared:
    name: Build MXE i686-w64-mingw32.shared
    runs-on: ubuntu-latest
    container: opensuse/leap:15.3
    steps:
      - uses: actions/checkout@v1.2.0
      - name: Add devel-tools-building repo
        run: zypper -n ar -c -f -n 'repo-devel-tools-building' https://download.opensuse.org/repositories/devel:/tools:/building/openSUSE_Leap_15.3/ repo-devel-tools-building
      - name: Update packages
        run: zypper -n --gpg-auto-import-keys ref
      - name: Upgrade packages
        run: zypper -n --gpg-auto-import-keys up
      - name: Install openSUSE dependencies
        run: zypper -n --gpg-auto-import-keys install glibc glibc-extra glibc-locale glibc-i18ndata glibc-32bit gcc10 gcc10-c++ shadow which patch gperf wget curl git diffutils make cmake libtool pkg-config autoconf automake makeinfo meson ninja intltool tar gzip bzip2 xz p7zip p7zip-full lzip zip unzip gtk-doc gettext-tools scons bison flex ruby orc linux-glibc-devel glibc-devel file-devel libopenssl-devel libffi-devel gdk-pixbuf-devel python3-base python3-Mako
      - name: update-alternatives
        run: |
          update-alternatives --install /usr/bin/cc cc /usr/bin/gcc-10 50
          update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-10 50
          update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 50
          update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 50
          update-alternatives --set cc /usr/bin/gcc-10
          update-alternatives --set c++ /usr/bin/g++-10
          update-alternatives --set gcc /usr/bin/gcc-10
          update-alternatives --set g++ /usr/bin/g++-10
      - name: Link python 3
        run: ln -s /usr/bin/python3 /usr/bin/python
      - name: Update settings.mk
        shell: bash
        run: sed -i 's/MXE_TARGETS := .*/MXE_TARGETS := i686-w64-mingw32.shared/g' settings.mk
      - name: Compile
        shell: bash
        run: make -j4

  build-x86_64-w64-mingw32-shared:
    name: Build MXE x86_64-w64-mingw32.shared
    runs-on: ubuntu-latest
    container: opensuse/leap:15.3
    steps:
      - uses: actions/checkout@v1.2.0
      - name: Add devel-tools-building repo
        run: zypper -n ar -c -f -n 'repo-devel-tools-building' https://download.opensuse.org/repositories/devel:/tools:/building/openSUSE_Leap_15.3/ repo-devel-tools-building
      - name: Update packages
        run: zypper -n --gpg-auto-import-keys ref
      - name: Upgrade packages
        run: zypper -n --gpg-auto-import-keys up
      - name: Install openSUSE dependencies
        run: zypper -n --gpg-auto-import-keys install glibc glibc-extra glibc-locale glibc-i18ndata glibc-32bit gcc10 gcc10-c++ shadow which patch gperf wget curl git diffutils make cmake libtool pkg-config autoconf automake makeinfo meson ninja intltool tar gzip bzip2 xz p7zip p7zip-full lzip zip unzip gtk-doc gettext-tools scons bison flex ruby orc linux-glibc-devel glibc-devel file-devel libopenssl-devel libffi-devel gdk-pixbuf-devel python3-base python3-Mako
      - name: update-alternatives
        run: |
          update-alternatives --install /usr/bin/cc cc /usr/bin/gcc-10 50
          update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-10 50
          update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 50
          update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 50
          update-alternatives --set cc /usr/bin/gcc-10
          update-alternatives --set c++ /usr/bin/g++-10
          update-alternatives --set gcc /usr/bin/gcc-10
          update-alternatives --set g++ /usr/bin/g++-10
      - name: Link python 3
        run: ln -s /usr/bin/python3 /usr/bin/python
      - name: Update settings.mk
        shell: bash
        run: sed -i 's/MXE_TARGETS := .*/MXE_TARGETS := x86_64-w64-mingw32.shared/g' settings.mk
      - name: Compile
        shell: bash
        run: make -j4


  build-docker-i686-w64-mingw32-static:
    name: Build Docker i686-w64-mingw32.static
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.2.0
      - uses: docker/build-push-action@v1
        with:
          dockerfile: ./dockerfiles/i686-w64-mingw32.static
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: jonaski/mxe-qt-i686-w64-mingw32.static
          tags: latest

  build-docker-i686-w64-mingw32-shared:
    name: Build Docker i686-w64-mingw32.shared
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.2.0
      - uses: docker/build-push-action@v1
        with:
          dockerfile: ./dockerfiles/i686-w64-mingw32.shared
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: jonaski/mxe-qt-i686-w64-mingw32.shared
          tags: latest

  build-docker-x86_64-w64-mingw32-static:
    name: Build Docker x86_64-w64-mingw32.static
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.2.0
      - uses: docker/build-push-action@v1
        with:
          dockerfile: ./dockerfiles/x86_64-w64-mingw32.static
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: jonaski/mxe-qt-x86_64-w64-mingw32.static
          tags: latest

  build-docker-x86_64-w64-mingw32-shared:
    name: Build Docker x86_64-w64-mingw32.shared
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.2.0
      - uses: docker/build-push-action@v1
        with:
          dockerfile: ./dockerfiles/x86_64-w64-mingw32.shared
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: jonaski/mxe-qt-x86_64-w64-mingw32.shared
          tags: latest
