name: C/C++ CI
on: [push, pull_request]

jobs:
  build-i686-w64-mingw32-static:
    name: Build MXE i686-w64-mingw32.static
    runs-on: ubuntu-latest
    container: opensuse/leap:15.4
    steps:
      - name: Add devel-tools-building repo
        run: zypper -n ar -c -f -n 'repo-devel-tools-building' https://download.opensuse.org/repositories/devel:/tools:/building/15.4/ repo-devel-tools-building
      - name: Update packages
        run: zypper -n --gpg-auto-import-keys ref
      - name: Upgrade packages
        run: zypper -n --gpg-auto-import-keys up
      - name: Install openSUSE dependencies
        run: zypper -n --gpg-auto-import-keys install glibc glibc-extra glibc-locale glibc-i18ndata glibc-32bit gcc11 gcc11-c++ shadow which patch gperf wget curl git diffutils make cmake libtool pkg-config autoconf automake makeinfo meson ninja intltool tar gzip bzip2 xz p7zip p7zip-full lzip zip unzip gtk-doc gettext-tools scons bison flex ruby orc linux-glibc-devel glibc-devel file-devel libopenssl-devel libffi-devel gdk-pixbuf-devel python3-base python3-Mako libzstd-devel pcre2-devel
      - name: update-alternatives
        run: |
          update-alternatives --install /usr/bin/cc cc /usr/bin/gcc-11 50
          update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-11 50
          update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 50
          update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 50
          update-alternatives --set cc /usr/bin/gcc-11
          update-alternatives --set c++ /usr/bin/g++-11
          update-alternatives --set gcc /usr/bin/gcc-11
          update-alternatives --set g++ /usr/bin/g++-11
      - name: Link python 3
        run: ln -s /usr/bin/python3 /usr/bin/python
      - name: Patch meson
        run: |
          cd /tmp
          wget https://patch-diff.githubusercontent.com/raw/mesonbuild/meson/pull/9841.patch
          cd /usr/lib/python3.6/site-packages
          patch -p1 < /tmp/9841.patch
      - uses: actions/checkout@v3
      - name: Add safe git directory
        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}
      - name: Update settings.mk
        shell: bash
        run: sed -i 's/MXE_TARGETS := .*/MXE_TARGETS := i686-w64-mingw32.static/g' settings.mk
      - name: Compile
        shell: bash
        run: make -j 4

  build-x86_64-w64-mingw32-static:
    name: Build MXE x86_64-w64-mingw32.static
    runs-on: ubuntu-latest
    container: opensuse/leap:15.4
    steps:
      - name: Add devel-tools-building repo
        run: zypper -n ar -c -f -n 'repo-devel-tools-building' https://download.opensuse.org/repositories/devel:/tools:/building/15.4/ repo-devel-tools-building
      - name: Update packages
        run: zypper -n --gpg-auto-import-keys ref
      - name: Upgrade packages
        run: zypper -n --gpg-auto-import-keys up
      - name: Install openSUSE dependencies
        run: zypper -n --gpg-auto-import-keys install glibc glibc-extra glibc-locale glibc-i18ndata glibc-32bit gcc11 gcc11-c++ shadow which patch gperf wget curl git diffutils make cmake libtool pkg-config autoconf automake makeinfo meson ninja intltool tar gzip bzip2 xz p7zip p7zip-full lzip zip unzip gtk-doc gettext-tools scons bison flex ruby orc linux-glibc-devel glibc-devel file-devel libopenssl-devel libffi-devel gdk-pixbuf-devel python3-base python3-Mako libzstd-devel pcre2-devel
      - name: update-alternatives
        run: |
          update-alternatives --install /usr/bin/cc cc /usr/bin/gcc-11 50
          update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-11 50
          update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 50
          update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 50
          update-alternatives --set cc /usr/bin/gcc-11
          update-alternatives --set c++ /usr/bin/g++-11
          update-alternatives --set gcc /usr/bin/gcc-11
          update-alternatives --set g++ /usr/bin/g++-11
      - name: Link python 3
        run: ln -s /usr/bin/python3 /usr/bin/python
      - name: Patch meson
        run: |
          cd /tmp
          wget https://patch-diff.githubusercontent.com/raw/mesonbuild/meson/pull/9841.patch
          cd /usr/lib/python3.6/site-packages
          patch -p1 < /tmp/9841.patch
      - uses: actions/checkout@v3
      - name: Add safe git directory
        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}
      - name: Update settings.mk
        shell: bash
        run: sed -i 's/MXE_TARGETS := .*/MXE_TARGETS := x86_64-w64-mingw32.static/g' settings.mk
      - name: Compile
        shell: bash
        run: make -j 4

  build-i686-w64-mingw32-shared:
    name: Build MXE i686-w64-mingw32.shared
    runs-on: ubuntu-latest
    container: opensuse/leap:15.4
    steps:
      - name: Add devel-tools-building repo
        run: zypper -n ar -c -f -n 'repo-devel-tools-building' https://download.opensuse.org/repositories/devel:/tools:/building/15.4/ repo-devel-tools-building
      - name: Update packages
        run: zypper -n --gpg-auto-import-keys ref
      - name: Upgrade packages
        run: zypper -n --gpg-auto-import-keys up
      - name: Install openSUSE dependencies
        run: zypper -n --gpg-auto-import-keys install glibc glibc-extra glibc-locale glibc-i18ndata glibc-32bit gcc11 gcc11-c++ shadow which patch gperf wget curl git diffutils make cmake libtool pkg-config autoconf automake makeinfo meson ninja intltool tar gzip bzip2 xz p7zip p7zip-full lzip zip unzip gtk-doc gettext-tools scons bison flex ruby orc linux-glibc-devel glibc-devel file-devel libopenssl-devel libffi-devel gdk-pixbuf-devel python3-base python3-Mako libzstd-devel pcre2-devel
      - name: update-alternatives
        run: |
          update-alternatives --install /usr/bin/cc cc /usr/bin/gcc-11 50
          update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-11 50
          update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 50
          update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 50
          update-alternatives --set cc /usr/bin/gcc-11
          update-alternatives --set c++ /usr/bin/g++-11
          update-alternatives --set gcc /usr/bin/gcc-11
          update-alternatives --set g++ /usr/bin/g++-11
      - name: Link python 3
        run: ln -s /usr/bin/python3 /usr/bin/python
      - name: Patch meson
        run: |
          cd /tmp
          wget https://patch-diff.githubusercontent.com/raw/mesonbuild/meson/pull/9841.patch
          cd /usr/lib/python3.6/site-packages
          patch -p1 < /tmp/9841.patch
      - uses: actions/checkout@v3
      - name: Add safe git directory
        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}
      - name: Update settings.mk
        shell: bash
        run: sed -i 's/MXE_TARGETS := .*/MXE_TARGETS := i686-w64-mingw32.shared/g' settings.mk
      - name: Compile
        shell: bash
        run: make -j 4

  build-x86_64-w64-mingw32-shared:
    name: Build MXE x86_64-w64-mingw32.shared
    runs-on: ubuntu-latest
    container: opensuse/leap:15.4
    steps:
      - name: Add devel-tools-building repo
        run: zypper -n ar -c -f -n 'repo-devel-tools-building' https://download.opensuse.org/repositories/devel:/tools:/building/15.4/ repo-devel-tools-building
      - name: Update packages
        run: zypper -n --gpg-auto-import-keys ref
      - name: Upgrade packages
        run: zypper -n --gpg-auto-import-keys up
      - name: Install openSUSE dependencies
        run: zypper -n --gpg-auto-import-keys install glibc glibc-extra glibc-locale glibc-i18ndata glibc-32bit gcc11 gcc11-c++ shadow which patch gperf wget curl git diffutils make cmake libtool pkg-config autoconf automake makeinfo meson ninja intltool tar gzip bzip2 xz p7zip p7zip-full lzip zip unzip gtk-doc gettext-tools scons bison flex ruby orc linux-glibc-devel glibc-devel file-devel libopenssl-devel libffi-devel gdk-pixbuf-devel python3-base python3-Mako libzstd-devel pcre2-devel
      - name: update-alternatives
        run: |
          update-alternatives --install /usr/bin/cc cc /usr/bin/gcc-11 50
          update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-11 50
          update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 50
          update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 50
          update-alternatives --set cc /usr/bin/gcc-11
          update-alternatives --set c++ /usr/bin/g++-11
          update-alternatives --set gcc /usr/bin/gcc-11
          update-alternatives --set g++ /usr/bin/g++-11
      - name: Link python 3
        run: ln -s /usr/bin/python3 /usr/bin/python
      - name: Patch meson
        run: |
          cd /tmp
          wget https://patch-diff.githubusercontent.com/raw/mesonbuild/meson/pull/9841.patch
          cd /usr/lib/python3.6/site-packages
          patch -p1 < /tmp/9841.patch
      - uses: actions/checkout@v3
      - name: Add safe git directory
        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}
      - name: Update settings.mk
        shell: bash
        run: sed -i 's/MXE_TARGETS := .*/MXE_TARGETS := x86_64-w64-mingw32.shared/g' settings.mk
      - name: Compile
        shell: bash
        run: make -j 4


  build-docker-i686-w64-mingw32-static:
    name: Build Docker i686-w64-mingw32.static
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/ci'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Add safe git directory
        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push to DockerHub
        uses: docker/build-push-action@v3
        with:
          file: ./dockerfiles/i686-w64-mingw32.static
          push: true
          tags: jonaski/mxe-qt-i686-w64-mingw32.static:latest

  build-docker-i686-w64-mingw32-shared:
    name: Build Docker i686-w64-mingw32.shared
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/ci'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Add safe git directory
        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push to DockerHub
        uses: docker/build-push-action@v3
        with:
          file: ./dockerfiles/i686-w64-mingw32.shared
          push: true
          tags: jonaski/mxe-qt-i686-w64-mingw32.shared:latest

  build-docker-x86_64-w64-mingw32-static:
    name: Build Docker x86_64-w64-mingw32.static
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/ci'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Add safe git directory
        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push to DockerHub
        uses: docker/build-push-action@v3
        with:
          file: ./dockerfiles/x86_64-w64-mingw32.static
          push: true
          tags: jonaski/mxe-qt-x86_64-w64-mingw32.static:latest

  build-docker-x86_64-w64-mingw32-shared:
    name: Build Docker x86_64-w64-mingw32.shared
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/ci'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Add safe git directory
        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push to DockerHub
        uses: docker/build-push-action@v3
        with:
          file: ./dockerfiles/x86_64-w64-mingw32.shared
          push: true
          tags: jonaski/mxe-qt-x86_64-w64-mingw32.shared:latest
